#!/usr/bin/env bash
# Bash script that gives info about your Domain and Subdomain
if [ "$#" -eq 2 ]; then
    subdomains=$2
else
    subdomains=("www" "lb-01" "web-01" "web-02")
fi
for subdomain in "${subdomains[@]}"; do
    echo -n "The subdomain $subdomain"
    dig "$subdomain.$1" | grep -A1 'ANSWER SECTION:' | tail -n -1 | awk '{ print " is a " $4 " record and points to " $5}'
done
