#!/usr/bin/env bash
# Y U no love me?!
echo "$$" >> /var/run/holberontscript.pid
trap "echo I hate the kill command; rm /var/run/holberontscript.pid; exit" SIGTERM SIGQUIT
trap "echo Y U no love me?!; exit" SIGINT
while true
do
    echo "To infinity and beyond"
    sleep 2
done
