#!/usr/bin/env bash
# Parent of file "manage_my_process"

case $1 in
    start)
	echo "manage_my_process started"
	./manage_my_process &
	echo "$!" > /var/run/my_process.pid
	;;
    stop)
	echo "manage_my_process stopped"
	pkill -f "./manage_my_process"
	rm /var/run/my_process.pid
	;;
    restart)
	echo "manage_my_process restarted"
	pkill -f "./manage_my_process"
	./manage_my_process &
	echo "$!" > /var/run/my_process.pid
	;;
    *) echo "Usage: manage_my_process {start|stop|restart}"
esac
