#!/usr/bin/env bash
# prints fizz if multiple of 3, buzz of multiple of 5, fizzbuzz if both else just number
i=1
while [ $i -lt 101 ]; do
    if [[ $((i % 3)) == 0 && $((i % 5)) == 0 ]];
	then
	echo "FizzBuzz"
    elif [[ $((i % 3)) == 0 ]];
	then
	echo "Fizz"
    elif [[ $((i % 5)) == 0 ]];
	then
	echo "Buzz"
    else
	echo "$i"
    fi
    let i=i+1
done
