#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd
# Only username, user id, and home directory path for the user

while read LINE; do
    echo "$LINE" | cut -d":" -f1,3,6
done < /etc/passwd
