#!/usr/bin/env bash
#prints "bad luck" for 4th iteration, "good luck" for 8th, otherwise "Holberton School"
i=0
while [ $i -lt 10 ]; do
    if [ $i == 4 ]; then
	echo "bad luck"
    elif [ $i == 8 ]; then
	echo "good luck"
    else
	echo "Holberton School"
    fi
    let i=i+1
done
