#!/usr/bin/env bash
#prints "Holberton School" 10 times using while loop
i=1
m=1
while [ $i -lt 13 ]; do
    while [ $m -lt 60 ]; do
	echo $m
	let m=m+1
    done
    echo "Hour: $i"
    m=1
    let i=i+1
done
