#!/usr/bin/env bash
#prints minutes and hours until 12 hours is reached
i=0
m=1
while [ $i -lt 13 ]; do
    echo "Hour: $i"
    while [ $m -lt 60 ]; do
	echo $m
	let m=m+1
    done
    let i=i+1
    m=1
done
