#!/usr/bin/env bash
# Transfer File to Webserver
# $1 = File Path
# $2 = Webserver's IP address
# $3 = Username
# $4 = SSH public key location
if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -i "$4" "$1" "$3@$2:~/"
fi
