#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
apt-get -y update
apt-get install -y nginx
new_string="location /redirect_me {\n\t\trewrite ^(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t}\n"
sed -i "/# Only/a$new_string" /etc/nginx/sites-available/default
restart service nginx
