#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
old_error="#error_page"
new_error="error_page"
sed -i "s/$old_error/$new_error/" /etc/nginx/sites-available/default
service nginx restart
