#!/usr/bin/env bash
# Troubleshooting a webserver
if [ ! -f "/usr/sbin/apache2" ]; then
    echo "Apache is not installed"
fi
if [ ! -f "/usr/sbin/nginx" ]; then
    echo "nginx is not installed"
fi
# Restarting Service
sudo service apache2 restart
