#!/usr/bin/env bash
#prints "Holberton School" 10 times using while loop
i=0
while [ $i -lt 10 ]; do
    if $(($i % 4)); then
	echo "bad luck"
    elif $(($1 % 8)); then
	echo "good luck"
    else
	echo "Holberton School"
	let i=i+1
    fi
done
