#!/usr/bin/env bash
#nginx must be running as nginx user
sudo service nginx stop
sed -i 's/www-data/nginx/g' /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sudo service nginx start
sudo service nginx restart
